create database customer_behavior;

use customer_behavior;
select * from mytable limit 20;

-- What is the total revenue generated by male and female customers?
select gender, SUM(purchase_amount) as revenue
from mytable
group by gender;

-- Which customers used a discount but still spent more than avrage purchase amount?
select customer_id, purchase_amount
from mytable
where discount_applied = 'Yes' and purchase_amount >= (select Avg(purchase_amount) from mytable);

-- Which are the top 5 products with the highest average review rating?
select item_purchased, Round(AVG(review_rating), 2) as "Average Review Rating"
from mytable
group by item_purchased
order by avg(review_rating) desc
limit 5;

-- Compare the average purchase amounts between standard and express shipping?
select shipping_type, round(avg(purchase_amount), 2) as "Avg Purchase Amount"
from mytable
where shipping_type in ('Standard', 'Express')
group by shipping_type;

-- Do subscribed customes spend more? Compare average spent and total revenue between subscribers and non-subscribers.
select subscription_status,
COUNT(customer_id) as total_customers,
Round(Avg(purchase_amount), 2) as avg_spend,
Round(Avg(purchase_amount), 2) as total_revenue
from mytable
group by subscription_status
order by total_revenue, avg_spend desc;

-- Which 5 products have the highest percentage of purchase with discounts applied?
select item_purchased,
ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*), 2) as Discount_Rate
from mytable
group by item_purchased
order by Discount_Rate Desc
limit 5;

-- Segment customers into New, Returning and Loyal based on their total number of previous purchase and show the count of each segment
with customer_type as (
select customer_id, previous_purchases,
CASE 
	WHEN previous_purchases = 1 THEN 'New Customer'
    WHEN previous_purchases between 2 and 10 THEN 'Returning Customer'
    ELSE 'Loyal Customer'
    END as customer_segment																																																																																																																
from mytable
)
select customer_segment, count(*) as "Number of Customers"
from customer_type
group by customer_segment

-- What are the top 3 most purchased products within eac category?
with item_counts as (
select category,
item_purchased,
COUNT(customer_id) as total_orders,
ROW_NUMBER() over(partition by category order by count(customer_id) Desc) as item_rank
from mytable
group by category, item_purchased
)

select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <=3;

-- Are customers who are repeat buyer (more than 5 previous puchase) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from mytable
where previous_purchases > 5
group by subscription_status

-- What is the revenue contribution of each age group
select age_group,
sum(purchase_amount) as total_revenue
from mytable
group by age_group
order by total_revenue desc;